version: "3"

services:
  api:
    container_name: my-api
    build: ./
    restart: on-failure # use always - production
    volumes:
      - ./:/mycode
    ports:
      - 5000:5000
    # command: tail -f /dev/null
    # command: python manage.py run
    # command: gunicorn -c /mycode/gunicorn.conf.py manage:run
    command: gunicorn --bind 0.0.0.0:5000 -w 4 manage:app
